# Generated by Django 4.0.1 on 2022-01-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_nft_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection',
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_choice_text', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_nft_app.item')),
            ],
        ),
    ]
