# Generated by Django 4.0.1 on 2022-01-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_nft_app', '0002_remove_item_collection_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection',
            new_name='item',
        ),
    ]
