# Generated by Django 4.0.1 on 2022-02-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_nft_app', '0005_rename_collection_collection_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
