# Generated by Django 4.0.1 on 2022-02-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_nft_app', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='item',
            new_name='collection',
        ),
    ]
